---
services:
  - name: docker:dind

variables:
  #  # disable TLS; see: https://gitlab.com/gitlab-org/gitlab-runner/issues/1350#note_199840999 and https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - lint
  - test

lint:
  stage: lint
  parallel:
    matrix:
      - PYTHON_VERSION:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
  image: python:$PYTHON_VERSION
  script:
    - pip3 install yamllint
    - yamllint .
  allow_failure: true

molecule:
  stage: test
  parallel:
    matrix:
      - MOLECULE_DISTRO:
          - ubuntu1604
          - ubuntu2204
        PYTHON_VERSION:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
  image: python:$PYTHON_VERSION
  variables:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
  script:
    - apt-get update
    - apt-get install -y docker.io python3-pip
    - docker version
    - pip3 install ansible molecule molecule-plugins[docker] docker pytest pytest-testinfra
    - molecule test --all
