---
services:
  - name: docker:dind

variables:
  #  # disable TLS; see: https://gitlab.com/gitlab-org/gitlab-runner/issues/1350#note_199840999 and https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - lint
  - test

lint:
  stage: lint
  parallel:
    matrix:
      - PYTHON_VERSION: "3.10"
      - PYTHON_VERSION: "3.11"
      - PYTHON_VERSION: "3.12"
  image: python:$PYTHON_VERSION
  script:
    - pip3 install yamllint
    - yamllint .

molecule:
  stage: test
  image: python:3.10
  variables:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
  parallel:
    matrix:
      - MOLECULE_DISTRO:
          - ubuntu1604
          - ubuntu2204
  script:
    - apt-get update
    - apt-get install -y docker.io
    - docker version
    - docker run hello-world
    - apt-get update && apt-get install -y python3-pip
    - pip3 install ansible molecule molecule-plugins[docker] docker pytest pytest-testinfra
    - molecule test --all
