---
name: CI

"on":
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu:24.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu:24.04
    strategy:
      matrix:
        include:
          # The distributions that `molecule` will spin up in docker to test against.
          # Must be available at `geerlingguy/docker-${distribution}-ansible:latest`
          - distribution: ubuntu2204 
          - distribution: ubuntu2404
          - distribution: ubuntu2604

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker pytest pytest-testinfra

      - name: Run Molecule tests.
        run: molecule test --all
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distribution }}
